apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservices
spec:
  selector:
    app: product-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  
