---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: microservices
spec:
  selector:
    app: front-service
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31888
 