apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices
spec:
  selector:
    app: auth-service      # doit correspondre au label de ton Deployment auth-service
  type: ClusterIP      
  ports:
    - protocol: TCP
      port: 3000       # port interne du service
      targetPort: 3000 # port du container backend
     
