# Utiliser l'image officielle Nginx comme base
FROM nginx:latest

# Copier le fichier de configuration nginx personnalisé dans le conteneur
COPY default.conf /etc/nginx/conf.d/default.conf


# Exposer le port 80 pour Nginx
EXPOSE 80
