apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: microservices
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXNfYXV0aA==  # "postgres_auth" encodé en base64
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=  # "postgres_password" encodé en base64
  
