apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microservices
spec:
  selector:
    app: order-service      # doit correspondre au label de ton Deployment order-service
  type: ClusterIP      
  ports:
    - protocol: TCP
      port: 3002       
      targetPort: 3002 
